name: Hassfest validation
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hassfest
        run: |
          container=$(docker create -w /workspace ghcr.io/home-assistant/hassfest)
          docker cp "${{ github.workspace }}/." "$container:/workspace"
          docker start -a "$container"; ec=$?; docker rm "$container"; exit $ec
