name: Hassfest validation
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hassfest
        run: docker run --rm -v ${{ github.workspace }}://github/workspace ghcr.io/home-assistant/hassfest --integration-path //github/workspace/custom_components/discord_webhook
